```{r}
num_individuals <- rep(c(10, 20, 30, 40, 50), each = 10)
num_markers <- rep(c(10, 20, 30, 40, 50, 60, 70, 80, 90, 100), times = 5)
type <- rep(c("T", "R"), each = 50)
accuracy <- rep(NA, 50)  
result <- data.frame(`Num of Individuals` = num_individuals,`Num of Markers` = num_markers,`Type` = type, `Accuracy` = accuracy)

result$Accuracy <- NULL

replicate_columns <- paste0("Replicate ", 1:20)
for(col in replicate_columns) {
  result[[col]] <- NA
}

```


```{r}
library(tidyverse)
dfCLM = read_delim("CLM_unrels.raw", delim = "\t") 
dfPUR = read_delim("PUR_unrels.raw", delim = "\t") 
dfCLM <- dfCLM[1:88, 7:10006]
dfPUR <- dfPUR[1:88, 7:10006]
```


```{r}
markers <- colnames(dfPUR)
markers2<-markers
frequencies <- colSums(dfPUR) / (2 * 88)
frequencies <- as.numeric(frequencies)
freq_PUR <- data.frame(markers, frequencies)

frequencies2 <- colSums(dfCLM) / (2 * 88)
frequencies2 <- as.numeric(frequencies2)
freq_CLM <- data.frame(markers2, frequencies2)


Fst_list <- vector("numeric", length = 10000)
for(i in 1:10000){
  p1 = freq_PUR[i,2]
  q1 = 1-p1
  p2 = freq_CLM[i,2]
  q2 = 1-p2
  pbar = (p1+p2)/2
  qbar = (q1+q2)/2
  varp = ((pbar-p1)^2 + (pbar-p2)^2)/2
  Fst <- varp/(pbar * qbar)
  Fst_list[i] <- Fst
}

nan_positions <- which(is.nan(Fst_list))
Fst_list[nan_positions] <- 0
N <- 100
top_indices<- order(unlist(Fst_list), decreasing = TRUE)[1:N]
freq_PUR$frequencies[freq_PUR$frequencies == 0] <- 0.00001
freq_CLM$frequencies2[freq_CLM$frequencies2 == 0] <- 0.00001
freq_PUR$frequencies[freq_PUR$frequencies == 1] <- 0.99999
freq_CLM$frequencies2[freq_CLM$frequencies2 == 1] <- 0.99999
```


```{r}
#compute delta
k = 88
m = 10000
deltaPUR = data.frame(k, m)
for(i in 1:k){
  for(j in 1:m){
    if(dfPUR[i,j] == 1){
      deltaPUR[i,j] = 0
    }else{
      deltaPUR[i,j] = 1
    }
  }
}
deltaCLM = data.frame(k, m)
for(i in 1:k){
  for(j in 1:m){
    if(dfCLM[i,j] == 1){
      deltaCLM[i,j] = 0
    }else{
      deltaCLM[i,j] = 1
    }
  }
}
```

```{r}
dcontrol <- 20
k = 1 # control number of individuals
for(w in 1:5){
  k = w*10
  print(paste("num of individuals:", k))
  for(x in 1:10){
    m <- x*10
    print("Top   ")
    print(paste("num of Markers:", m))
    ppl1value = numeric(k)
  for(i in 1:k){
    ppl1value[i] = 1
  }

  for(i in 1:k){
    for(j in 1:m){
      if(dfPUR[i,top_indices[j]] == 2){
        ppl1value[i] = ppl1value[i]*(2-deltaPUR[i,top_indices[j]])*freq_PUR[top_indices[j], 2]*freq_PUR[top_indices[j], 2]
      }
      else if(dfPUR[i,top_indices[j]]== 0){
        ppl1value[i] = ppl1value[i]*(2-deltaPUR[i,top_indices[j]])*(1-freq_PUR[top_indices[j], 2])*(1-freq_PUR[top_indices[j], 2])
      }
      else {
        ppl1value[i] = ppl1value[i]*(2-deltaPUR[i,top_indices[j]])*freq_PUR[top_indices[j], 2]*(1-freq_PUR[top_indices[j], 2])
      }
    }
  }
     ppl2value = numeric(k)
  for(i in 1:k){
    ppl2value[i] = 1
  }
  for(i in 1:k){
    for(j in 1:m){
      if(dfPUR[i,top_indices[j]] == 2){
        ppl2value[i] = ppl2value[i]*(2-deltaPUR[i,top_indices[j]])*freq_CLM[top_indices[j], 2]*freq_CLM[top_indices[j], 2]
      }
      else if(dfPUR[i,top_indices[j]] == 0){
        ppl2value[i] = ppl2value[i]*(2-deltaPUR[i,top_indices[j]])*(1-freq_CLM[top_indices[j], 2])*(1-freq_CLM[top_indices[j], 2])
      }
      else {
        ppl2value[i] = ppl2value[i]*(2-deltaPUR[i,top_indices[j]])*freq_CLM[top_indices[j], 2]*(1-freq_CLM[top_indices[j], 2])
      }
    }
  }
  matrix1 <- matrix(1, nrow = 1, ncol = k)
  for(i in 1:k){
    if(ppl1value[i] >= ppl2value[i]){
      matrix1[i] = 1
    }else
      matrix1[i] = 2
  }
  ppl1value = numeric(k)
  for(i in 1:k){
      ppl1value[i] = 1
  }
  for(i in 1:k){
    for(j in 1:m){
      if(dfCLM[i,top_indices[j]] == 2){
        ppl1value[i] = ppl1value[i]*(2-deltaCLM[i,top_indices[j]])*freq_PUR[top_indices[j], 2]*freq_PUR[top_indices[j], 2]
      }
      else if(dfCLM[i,top_indices[j]]== 0){
        ppl1value[i] = ppl1value[i]*(2-deltaCLM[i,top_indices[j]])*(1-freq_PUR[top_indices[j], 2])*(1-freq_PUR[top_indices[j], 2])
      }
      else {
        ppl1value[i] = ppl1value[i]*(2-deltaCLM[i,top_indices[j]])*freq_PUR[top_indices[j], 2]*(1-freq_PUR[top_indices[j], 2])
      }
    }
  }
  ppl2value = numeric(k)
  for(i in 1:k){
      ppl2value[i] = 1
  }
  for(i in 1:k){
    for(j in 1:m){
      if(dfCLM[i,top_indices[j]] == 2){
        ppl2value[i] = ppl2value[i]*(2-deltaCLM[i,top_indices[j]])*freq_CLM[top_indices[j], 2]*freq_CLM[top_indices[j], 2]
      }
      else if(dfCLM[i,top_indices[j]] == 0){
        ppl2value[i] = ppl2value[i]*(2-deltaCLM[i,top_indices[j]])*(1-freq_CLM[top_indices[j], 2])*(1-freq_CLM[top_indices[j], 2])
      }
      else {
        ppl2value[i] = ppl2value[i]*(2-deltaCLM[i,top_indices[j]])*freq_CLM[top_indices[j], 2]*(1-freq_CLM[top_indices[j], 2])
      }
    }
  }
  matrix2 <- matrix(0, nrow = 1, ncol = k)
  for(i in 1:k){
    if(ppl1value[i]>=ppl2value[i]){
      matrix2[i] = 1
    }else
      matrix2[i] = 2
  }
  library(caret)
  if (all(matrix1 == 2)) {
  accuracy <- 0.5
}
else if (all(matrix2 == 1)) {
  accuracy <- 0.5
}
else{
  actural_label <- matrix(c(rep(1, k), rep(2, k)), nrow = 2, ncol = k, byrow = TRUE)
  combined_matrix <- rbind(matrix1, matrix2)
  predicted_classes <- combined_matrix
  confusion_matrix<- confusionMatrix(table(predicted_classes, actural_label))
  accuracy <- confusion_matrix$overall["Accuracy"]
}
  l <- 0
  l <- (w-1)*10 + x
  #
  result[l,4] <- accuracy
  }
  for(y in 1:10){
    m <- y*10
    print("Random   ")
    print(paste("num of Markers:", m))
    sum = 0
    for(d in 1:dcontrol){
    set.seed(d)
    random_indices <- sample(1:10000, 140, replace = FALSE)
    ppl1value = numeric(k)
  for(i in 1:k){
    ppl1value[i] = 1
  }

  for(i in 1:k){
    for(j in 1:m){
      if(dfPUR[i,random_indices[j]] == 2){
        ppl1value[i] = ppl1value[i]*(2-deltaPUR[i,random_indices[j]])*freq_PUR[random_indices[j], 2]*freq_PUR[random_indices[j], 2]
      }
      else if(dfPUR[i,random_indices[j]] == 0){
        ppl1value[i] = ppl1value[i]*(2-deltaPUR[i,random_indices[j]])*(1-freq_PUR[random_indices[j], 2])*(1-freq_PUR[random_indices[j], 2])
      }
      else {
        ppl1value[i] = ppl1value[i]*(2-deltaPUR[i,random_indices[j]])*freq_PUR[random_indices[j], 2]*(1-freq_PUR[random_indices[j], 2])
      }
    }
  }
     ppl2value = numeric(k)
  for(i in 1:k){
    ppl2value[i] = 1
  }
  for(i in 1:k){
    for(j in 1:m){
      if(dfPUR[i,random_indices[j]] == 2){
        ppl2value[i] = ppl2value[i]*(2-deltaPUR[i,random_indices[j]])*freq_CLM[random_indices[j], 2]*freq_CLM[random_indices[j], 2]
      }
      else if(dfPUR[i,random_indices[j]] == 0){
        ppl2value[i] = ppl2value[i]*(2-deltaPUR[i,random_indices[j]])*(1-freq_CLM[random_indices[j], 2])*(1-freq_CLM[random_indices[j], 2])
      }
      else {
        ppl2value[i] = ppl2value[i]*(2-deltaPUR[i,random_indices[j]])*freq_CLM[random_indices[j], 2]*(1-freq_CLM[random_indices[j], 2])
      }
    }
  }

  matrix1 <- matrix(1, nrow = 1, ncol = k)
  for(i in 1:k){
    if(ppl1value[i] > ppl2value[i]){
      matrix1[i] = 1
    }else
      matrix1[i] = 2
  }
  ppl1value = numeric(k)
  for(i in 1:k){
      ppl1value[i] = 1
  }
  for(i in 1:k){
    for(j in 1:m){
      if(dfCLM[i,random_indices[j]] == 2){
        ppl1value[i] = ppl1value[i]*(2-deltaCLM[i,random_indices[j]])*freq_PUR[random_indices[j], 2]*freq_PUR[random_indices[j], 2]
      }
      else if(dfCLM[i,random_indices[j]]== 0){
        ppl1value[i] = ppl1value[i]*(2-deltaCLM[i,random_indices[j]])*(1-freq_PUR[random_indices[j], 2])*(1-freq_PUR[random_indices[j], 2])
      }
      else {
        ppl1value[i] = ppl1value[i]*(2-deltaCLM[i,random_indices[j]])*freq_PUR[random_indices[j], 2]*(1-freq_PUR[random_indices[j], 2])
      }
    }
  }
  ppl2value = numeric(k)
  for(i in 1:k){
      ppl2value[i] = 1
  }
  for(i in 1:k){
    for(j in 1:m){
      if(dfCLM[i,random_indices[j]] == 2){
        ppl2value[i] = ppl2value[i]*(2-deltaCLM[i,random_indices[j]])*freq_CLM[random_indices[j], 2]*freq_CLM[random_indices[j], 2]
      }
      else if(dfCLM[i,random_indices[j]]== 0){
        ppl2value[i] = ppl2value[i]*(2-deltaCLM[i,random_indices[j]])*(1-freq_CLM[random_indices[j], 2])*(1-freq_CLM[random_indices[j], 2])
      }
      else {
        ppl2value[i] = ppl2value[i]*(2-deltaCLM[i,random_indices[j]])*freq_CLM[random_indices[j], 2]*(1-freq_CLM[random_indices[j], 2])
      }
    }
  }
  matrix2 <- matrix(0, nrow = 1, ncol = k)
  for(i in 1:k){
    if(ppl1value[i]>ppl2value[i]){
      matrix2[i] = 1
    }else
      matrix2[i] = 2
  }
  library(caret)
  actural_label <- matrix(c(rep(1, k), rep(2, k)), nrow = 2, ncol = k, byrow = TRUE)
  combined_matrix <- rbind(matrix1, matrix2)
  predicted_classes <- combined_matrix
  confusion_matrix<- confusionMatrix(table(predicted_classes, actural_label))
  accuracy <- confusion_matrix$overall["Accuracy"]
  #sum = sum + accuracy
  l <- (w-1)*10 + 50 + y
  result[l,3+d] <- accuracy
   }
  # sum = sum/dcontrol
  # l <- 0
  # l <- (w-1)*10 + 50 + y
   #
  # result[l,4] <- sum
  }
}

```

```{r}
write.csv(result, file = "PURCLM.csv", row.names = FALSE)
```


```{r}
library(tidyverse)
data <- read.csv("PURCLM.csv")
data$accuracy <- NA
data$SD <- NA
data[data$Type == 'T', 'accuracy'] <- data[data$Type == 'T', 'Replicate.1']
data[data$Type == 'T', 'SD'] <- 0
replicate_cols <- grep("Replicate", names(data), value = TRUE)
data[data$Type == 'R', 'accuracy'] <- rowMeans(data[data$Type == 'R', replicate_cols], na.rm = TRUE)
data[data$Type == 'R', 'SD'] <- apply(data[data$Type == 'R', replicate_cols], 1, sd, na.rm = TRUE)
first_three <- data[, 1:3]
last_two <- data[, c('accuracy', 'SD')]
data <- cbind(first_three, last_two)
```

```{r}
library(ggplot2)

set.seed(120)  # reproducibility
data$jittered_x <- jitter(as.numeric(as.factor(data$`Num.of.Markers`)), amount = 0.3)

plot_PURCLM <- ggplot(data, aes(x = jittered_x, y = accuracy, shape = factor(Type), color = factor(`Num.of.Individuals`))) +
  geom_point(size = 3) + 
  geom_errorbar(aes(ymin = accuracy - 0.5*SD, ymax = accuracy + 0.5*SD, x = jittered_x), width = 0.2) +  # Use the same jittered x-coordinate for error bars
  labs(x = "Number of Markers", y = "Accuracy", color = "Number of Individuals", shape = "Marker Selection") +
  scale_shape_manual(values = c(21, 16), labels = c("Random", "Top")) + 
  scale_color_brewer(palette = "Set2") +  
  theme_bw() +
  theme(panel.background = element_rect(fill = "white"),
        text = element_text(size = 14),
        legend.title = element_text(size = 12),
        legend.text = element_text(size = 10))

# Save the plot
ggsave("plot_PURCLM_aligned_jitter.png", plot = plot_PURCLM, width = 10, height = 8, dpi = 300)
plot_PURCLM
```

```{r}
plot1 <- rep(NA, 100) 
plot2 <- rep(NA, 100) 
for (i in 1:100){
  plot1[i] <- freq_PUR[top_indices[i],2]
  plot2[i] <- freq_CLM[top_indices[i],2]
}

data <- data.frame(index = 1:100, plot1 = plot1, plot2 = plot2)

# Convert to long format
data_long <- pivot_longer(data, cols = c(plot1, plot2), names_to = "plot_type", values_to = "value")

# Create the plot with dots
a <- ggplot(data_long, aes(x = index, y = value, color = plot_type)) +
  geom_point() +  # Use geom_point for dots
  scale_color_manual(values = c("plot1" = "red", "plot2" = "blue"),labels = c("PUR", "CLM")) +
  labs(x = "Top# Fst Marker", y = "Allele Frequency", color = "Population") +
  theme_minimal()
ggsave("PURCLM_TopMarkers_AlleleFreqVsFst.png", plot = a, width = 10, height = 8, dpi = 300)
a
```

```{r}
library(tidyverse)

# Assuming 'data' is already defined as per your code

# Create the plot with dots and connecting lines, including a legend
b<- ggplot(data) +
  # Add points for plot1 with a color aesthetic for the legend
  geom_point(aes(x = index, y = plot1, color = "PUR"), size = 3) +
  # Add points for plot2 with a color aesthetic for the legend
  geom_point(aes(x = index, y = plot2, color = "CLM"), size = 3) +
  # Add segments connecting plot1 and plot2 points for each index, without affecting the legend
  geom_segment(aes(x = index, xend = index, y = plot1, yend = plot2), color = "black", show.legend = FALSE) +
  labs(x = "Top# Fst Marker", y = "Allele Frequency", color = "Population",title = "Frequency Gaps Between Top 100 Fst Markers") +
  scale_color_manual(values = c("PUR" = "red", "CLM" = "blue")) +
  theme_minimal()
ggsave("PURCLM_TopMarkers_FreGaps.png", plot = b, width = 10, height = 8, dpi = 300)
b
```
```{r}
gap <- rep(NA, 100) 
for (i in 1:100){
  gap[i] <- abs(freq_PUR[top_indices[i],2] - freq_CLM[top_indices[i],2])
}
library(tidyverse)
data_plot <- data.frame(Index = 1:100, 
                        Gap = gap, 
                        Fst = Fst_list[top_indices])
data_long <- pivot_longer(data_plot, cols = c(Gap, Fst), names_to = "Variable", values_to = "Value")

c<- ggplot(data_long, aes(x = Index, y = Value, color = Variable)) +
  geom_point() +  
  geom_smooth(method = "lm", se = FALSE) +  
  scale_color_manual(values = c("Gap" = "orange", "Fst" = "purple"), 
                     labels = c("Fst Values", "Frequency Gaps")) +  
  labs(x = "Top# Fst Marker", 
       y = "Value", 
       color = "Value Types") +  
  theme_minimal() 
ggsave("PURCLM_TopMarkers_FstValuesVsFreGaps.png", plot = c, width = 10, height = 8, dpi = 300)
c
```




